#!/bin/bash
# deplacer vers l'elevation DD
# usage movetoel DD MM Verbose;  DD=degrees MM=minute Verbose={Silent=0}
# minimum allowed elevation have to be set
#   
#    Copyright (C) 2010  Martin Aube
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#    Contact: martin.aube@cegepsherbrooke.qc.ca
#
let mind=5
let maxd=90
let flag=0
verbose=1
let speed=1
let del1=0
if [ "$1" = "" ]
then echo "usage: movetoel DD MM Verbose;  DD=degrees MM=minute Verbose={Silent=0}"
     exit 0
fi
if [ "$2" = "" ]
then echo "usage: movetoel DD MM Verbose;  DD=degrees MM=minute Verbose={Silent=0}"
     exit 0
fi
var=$1
if [ "$(echo $var |grep "^[ [:digit:] ]*$")" ]
then echo " "
else echo "bad degree format"
     exit 0
fi
var=$2
if [ "$(echo $var |grep "^[ [:digit:] ]*$")" ]
then echo " "
else echo "bad minute format"
     exit 0
fi
if [ "$3" != "" ]
then verbose=$3
fi
if [ $1 -lt $mind ]
then let dest="$mind"*60
     echo "Stopping at minimum allowed elevation: " $mind
else
   if [ $1 -gt $maxd ]
   then let dest="maxd"*60
        echo "Stopping at maximum allowed elevation: " $maxd
   else
     let dest="$1"*60+"$2"
   fi
fi
while [ "$flag" -eq 0 ]
do readmount "EL" $verbose
   read D M S < mount.tmp 
   if [ "$D" = "-00" ]
   then let M=M*-1
        let S=S*-1
   fi
   
   rm -f mount.tmp
   let min=D*60+M
   if [ "$dest" -lt "$min" ]
   then let delta=$min-$dest
   elif [ "$dest" -gt "$min" ]
   then let delta=$dest-$min
   else
      let delta=0
   fi
    if [ "$delta" -gt 300 ]
    then let speed=1
    fi
    if [ "$delta" -le 300 ]
    then let speed=2
    fi
    if [ "$delta" -le 60 ]
    then let speed=3
    fi
   if [ "$dest" -lt "$min" ]
   then action="movedown"
   elif [ "$dest" -gt "$min" ]
   then action="moveup"
   fi
if [ "$del1" -eq "$delta" ] 
        then
        if [ $verbose = "1" ] 
        then echo "arrived to destination"
        fi
        exit 0
fi
if [ "$delta" -eq 0 ] 
        then
        if [ $verbose = "1" ] 
        then echo "arrived to destination"
        fi
        exit 0
fi 
let del1=delta
if [ $verbose = "1" ] 
then echo $action
fi
   let de=delta/60
   let mi=delta-60*de
   $action $de $mi $speed
sleep 0.2
done
